from PLOD import controlGUI as cg
import multiWGPlot as mp
import h5py as h5
import sys
import tkinter as tk
import numpy as np
sys.path.append("Scripting")

def main( argv ):
    fname = ""
    for arg in argv:
        if ( arg.find("--file=") != -1 ):
            fname = arg.split("--file=")[1]
        elif ( arg.find("--help") != -1 ):
            print ("Usage: python plotMultiWG.py --file=<h5file> [--help]")
            print ("help: Print this message")
            print ("file: HDF5 file generated by the C++ application multiWG.out")
            return 0
        else:
            print ("Unknown argument %s"%(arg))
            return 1

    if ( fname == "" ):
        print ("No file given!")
        return 1

    multiplot = mp.MultiWGPlot()
    with h5.File( fname, 'r' ) as hf:
        dset = hf.get("amplitude")
        multiplot.zmin = dset.attrs.get("zmin")
        multiplot.zmax = dset.attrs.get("zmax")
        multiplot.xmin = dset.attrs.get("xmin")
        multiplot.xmax = dset.attrs.get("xmax")
        multiplot.R = np.zeros( int(dset.attrs.get("nWaveguides")) )
        multiplot.angles = np.zeros( len(multiplot.R) )
        uid = dset.attrs.get("uid")
        for i in range(0, len(multiplot.R)):
            multiplot.R[i] = dset.attrs.get( "R%d"%(i) )
            multiplot.angles[i] = dset.attrs.get( "angle%d"%(i) )

        intensity = np.array( dset )
        transmittivity = np.array( hf.get("transmittivity") )

    # Plot the datasets
    root = tk.Tk()
    ctl = cg.Control( root )
    fig, ax = multiplot.plotIntensity( intensity )
    ctl.attach( fig, ax, "Figures/multiWGIntensity%d"%(uid))

    figT, axT = multiplot.plotTransmittivity( transmittivity )
    ctl.attach( figT, axT, "Figures/multiWGTransmittivity%d"%(uid))
    root.mainloop()

if __name__ == "__main__":
    main( sys.argv[1:] )
