import sys
sys.path.append("../../FresnelFDTD")
sys.path.append("/home/david/Documents/BornAgain/install")
import mplLaTeX as ml
import matplotlib as mpl
mpl.rcParams.update(ml.params)
import numpy as np
import histogram2DParser as h2p
from matplotlib import pyplot as plt

MSG = "Usage: python visualizePattern.py --file=<datafile>\n"
MSG += "--help: Print this message\n"
MSG += "--file: 2D histogram file generated by the BornAgain code\n"

def main( argv ):
    fname = ""
    for arg in argv:
        if ( arg.find("--help") != -1 ):
            print MSG
            return 0
        elif ( arg.find("--file=") != -1 ):
            fname = arg.split("--file=")[1]
        else:
            print ("Unknown argument %s"%(arg))
            return 0

    if ( fname == "" ):
        print ("No filename specified")
        return 0

    reader = h2p.Histogram2D()
    reader.parse(fname)
    reader.display()
    reader.radToDeg()

    # Plot the pattern
    im = plt.imshow(reader.data.T, norm=mpl.colors.LogNorm(),
        extent=[reader.phi.min, reader.phi.max, reader.alpha.min, reader.alpha.max],
        aspect="auto", origin="lower")
    cb = plt.colorbar(im)
    cb.set_label("Intensity (a.u.)")
    plt.xlabel("$\phi_f$ (deg)")
    plt.ylabel("$\\alpha_f$ (deg)")
    ofname = "Fig/pattern2D.pdf"
    plt.savefig(ofname, bbox_inches="tight")
    print ("Figure written to %s"%(ofname))

if __name__ == "__main__":
    main(sys.argv[1:])
